name: Build and distribute

on:
push:
branches:
- main

env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
build:
name: Build Rayhan ai APK
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: zulu
      java-version: '17'

  - name: Setup Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable

  - name: Unzip Project File
    run: |
      unzip "Jarvis_AI_Complete_Project 2 .zip" -d extracted_project

      PROJECT_ROOT=$(find extracted_project -name "pubspec.yaml" -exec dirname {} \; | head -n 1)

      echo "PROJECT_PATH=$PROJECT_ROOT" >> $GITHUB_ENV

      echo "Project found at: $PROJECT_ROOT"

  - name: Fix Android V1 Embedding
    run: |
      cd "$PROJECT_PATH"

      MAIN_ACTIVITY=$(find android/app/src/main -name "MainActivity.kt" | head -n 1)

      echo "MainActivity path: $MAIN_ACTIVITY"

      cat << 'EOF' > "$MAIN_ACTIVITY"
      package com.jarvis.self_aware_automation

      import io.flutter.embedding.android.FlutterActivity

      class MainActivity: FlutterActivity()
      EOF

      echo "MainActivity fixed successfully!"

  - name: Install Dependencies
    run: |
      cd "$PROJECT_PATH"
      flutter pub get

  - name: Build APK
    run: |
      cd "$PROJECT_PATH"
      flutter build apk --release

  - name: Rename APK
    run: |
      cd "$PROJECT_PATH"

      mv build/app/outputs/flutter-apk/app-release.apk \
      build/app/outputs/flutter-apk/Rayhan_ai_2.apk

  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: Rayhan-ai-2.APK
      path: extracted_project/**/build/app/outputs/flutter-apk/Rayhan_ai_2.apk
